replicas: 1

serviceMonitor:
  enabled: true
  labels:
    release: prometheus

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.local
  tls:
    - secretName: tls
      hosts:
        - grafana.local

persistence:
  type: pvc
  enabled: true
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  size: 10Gi

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

smtp:
  existingSecret: grafana-smtp-secret
  userKey: "user"
  passwordKey: "password"

extraConfigmapMounts:
  - name: datasources
    configMap: grafana-datasources
    mountPath: /etc/grafana/provisioning/datasources
