alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
grafana:
  enabled: false
prometheus:
  enabled: true
  thanosService:
    enabled: false
  thanos:
    objectStorageConfig:
      secret:
        type: S3
        config:
          bucket: "thanos"
          endpoint: "minio:9000"
          access_key: "minioadmin"
          secret_key: "minioadmin"
          insecure: true
  prometheusSpec:
    replicas: 1
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
