deploymentMode: SimpleScalable
loki:
  auth_enabled: false
  limits_config:
    allow_structured_metadata: false
    retention_period: 7d
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-chunks
    type: s3
    s3:
      endpoint: minio.minio:9000
      secretAccessKey: minioadmin
      accessKeyId: minioadmin
      s3ForcePathStyle: true
      insecure: true
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

write:
  replicas: 1
  persistence:
    volumeClaimsEnabled: true
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    storageClass: longhorn

read:
  replicas: 1

backend:
  replicas: 1
  persistence:
    volumeClaimsEnabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClass: longhorn

ruler:
  enabled: false

monitoring:
  dashboards:
    enabled: true
  rules:
    enabled: true
    alerting: true
    labels:
      release: prometheus
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus