global:
  domain: argocd.local
  addPrometheusAnnotations: true

configs:
  params:
    server.insecure: true

controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

dex:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

redis:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

server:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
  ingress:
    enabled: true
    ingressClassName: nginx
    extraTls:
      - hosts: 
        - argocd.local
        secretName: tls

repoServer:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

applicationSet:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

notifications:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring


