auth:
  rootUser: minioadmin
  rootPassword: minioadmin
defaultBuckets: "thanos, loki-chunks"
mode: standalone
ingress:
  enabled: false
  ingressClassName: nginx
  hostname: minio.local
  tls: false
  extraHosts:
    - name: minio.local
    - path: /
  secrets:
    - name: tls
persistence:
  enabled: true
  storageClass: longhorn
  size: 20Gi
metrics:
  enabled: true
console:
  enabled: false
