alertmanager:
  enabled: true
  config:
    route:
      receiver: MSTeams
      routes:
      - matchers:
          - severity="warning"
        receiver: MSTeams
    receivers:
    - name: 'null'
    - name: 'MSTeams'
      msteamsv2_configs:
        - webhook_url: https://defaultcd67d1b788004d79a93f556a15d280.f2.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/e1783f53c4eb450490b6a32f51f0aeb1/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=xe517rPF9fqSESLbEEEaBguRSWJelyJDnMkVORszXs8
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  enabled: false
  
prometheus:
  enabled: true
  thanosService:
    enabled: false
  thanos:
    objectStorageConfig:
      secret:
        type: S3
        config:
          bucket: "thanos"
          endpoint: "minio:9000"
          access_key: "minioadmin"
          secret_key: "minioadmin"
          insecure: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.local
    tls:
      - secretName: tls
        hosts:
          - prometheus.local
  prometheusSpec:
    replicas: 1
    retention: 7d
    externalUrl: https://prometheus.local
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
