architecture: standalone

auth:
  enabled: true
  password: password
  existingSecret: ""
  existingSecretPasswordKey: ""

master:
  persistence:
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
    size: 8Gi

replica:
  kind: StatefulSet
  replicaCount: 1
  persistence:
    enabled: true
    path: /data
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
    size: 8Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
  prometheusRule:
    enabled: false
    additionalLabels: {}